export const BOATS_DATA = 'boats_data'
export const AUTH_STATE = 'auth_state'
export const MENU_STATE = 'menu_state'
export const AUTH_ERRORS = 'auth_errors'
export const REGISTER = 'register'
export const REGISTER_ERRORS = 'register_errors'